apiVersion: v1
kind: Service
metadata:
  name: {{.Name}}
  labels:
    app.kubernetes.io/name: http-server
    index: "{{.Index}}"
spec:
  selector:
    app.kubernetes.io/name: http-server
    index: "{{.Index}}"
    group: {{.group}}
  ports:
  - protocol: TCP
    port: 10000
    targetPort: 10000
    name: http
  type: ClusterIP
